Fix workflow

diff --git a/.github/workflows/ci.yaml b/.github/workflows/ci.yaml
--- a/.github/workflows/ci.yaml
+++ b/.github/workflows/ci.yaml
@@ -33,13 +33,13 @@ jobs:
           args: |
             /bin/sh -c "for file in $FILES; do
             echo -e '\x1b[1mCompiling' $file '\x1b[0m'
-            pandoc ./${file} -f latex -o './${file}.html' -t html --katex || echo -e '\x1b[31mError while compiling' $file '\x1b[0m'
+            pandoc ./${file} -f latex -o ./${file}.html -t html --katex || echo -e '\x1b[31mError while compiling' $file '\x1b[0m'
             done"
       - name: Push HTML back to repo
         if: ${{ !env.ACT }}
         uses: actions-x/commit@v2
         with:
-          message: Compiled LaTeX to HTML [job \#{{ env.GITHUB_JOB }}]
+          message: Compiled LaTeX to HTML [job \#${{ env.GITHUB_JOB }}]
       # - run: git add prueba.html
       # - run: git commit -m "Compile prueba.html"
       # - run: git push
