Updated workflow

diff --git a/.github/workflows/ci.yaml b/.github/workflows/ci.yaml
--- a/.github/workflows/ci.yaml
+++ b/.github/workflows/ci.yaml
@@ -9,21 +9,34 @@ on:
 jobs:
   build_all_latex:
     runs-on: ubuntu-latest
-    container: pandoc/latex
+    # container: pandoc/latex
     steps:
       # TODO Igual puedes hacerlo de tal forma que ejecute en pandoc/latex solo la parte de pasar a html, y la que es pillar los archivos cambiados en normal
       - name: Setup repo
         uses: actions/checkout@v2
         with:
           fetch-depth: 2 # To retrieve the preceding commit for changed files
-      - name: Compile to HTML all LaTeX
-        run: |
-          for file in `find -name '*.tex' -type f`; do
-            echo -e "\x1b[1mCompiling $file\x1b[0m"
-            pandoc "./${file}" -f latex -t html --katex
-          done
-      - run: pwd
+      # - name: Compile to HTML all LaTeX
+      #   run: |
+      #     for file in `find -name '*.tex' -type f`; do
+      #       echo -e "\x1b[1mCompiling $file\x1b[0m"
+      #       # pandoc "./${file}" -f latex -t html --katex
+      #       echo LAST_FILE=$file >> $GITHUB_ENV
+      #     done
+      - name: Get changed files
+        run: echo FILES=`git diff-tree --no-commit-id --name-only -r ${{ github.sha }} | grep -E "\.tex$"` >> $GITHUB_ENV
+      - name: Print changed git files
+        run: echo $FILES
+      - name: Compile to HTML from LaTeX
+        uses: docker://pandoc/latex
+        with:
+          args: |
+            /bin/sh -c "for file in $FILES; do
+            echo -e '\x1b[1mCompiling' $file '\x1b[0m'
+            pandoc ./${file} -f latex -o './${file}.html' -t html --katex || echo -e '\x1b[31mError while compiling' $file '\x1b[0m'
+            done"
       - name: Push HTML back to repo
+        if: ${{ !env.ACT }}
         uses: actions-x/commit@v2
         with:
           message: Compiled LaTeX to HTML [job \#{{ env.GITHUB_JOB }}]
